__rethrow_casa_exceptions = True
context = h_init()
context.set_state('ProjectSummary', 'proposal_code', '2018.1.00272.S')
context.set_state('ProjectSummary', 'piname', 'unknown')
context.set_state('ProjectSummary', 'proposal_title', 'unknown')
context.set_state('ProjectStructure', 'ous_part_id', 'X2015404445')
context.set_state('ProjectStructure', 'ous_title', 'Undefined')
context.set_state('ProjectStructure', 'ppr_file', '/opt/dared/opt/dared.2018OCT/mnt/dataproc/2018.1.00272.S_2019_03_01T21_35_09.197/SOUS_uid___A001_X133d_X963/GOUS_uid___A001_X133d_X964/MOUS_uid___A001_X133d_X967/working/PPR_uid___A001_X133d_X968.xml')
context.set_state('ProjectStructure', 'ps_entity_id', 'uid://A001/X12d7/X345')
context.set_state('ProjectStructure', 'recipe_name', 'hifa_cal')
context.set_state('ProjectStructure', 'ous_entity_id', 'uid://A001/X12d7/X341')
context.set_state('ProjectStructure', 'ousstatus_entity_id', 'uid://A001/X133d/X967')
try:
    hifa_importdata(vis=['uid___A002_Xd7842e_X1fca', 'uid___A002_Xd7842e_X2447', 'uid___A002_Xd79d9a_X41af'], dbservice=False, session=['session_1', 'session_1', 'session_2'])
    hifa_flagdata(pipelinemode="automatic")
    hifa_fluxcalflag(pipelinemode="automatic")
    hif_rawflagchans(pipelinemode="automatic")
    hif_refant(pipelinemode="automatic")
    h_tsyscal(pipelinemode="automatic")
    hifa_tsysflag(pipelinemode="automatic")
    hifa_antpos(pipelinemode="automatic")
    hifa_wvrgcalflag(pipelinemode="automatic")
    hif_lowgainflag(pipelinemode="automatic")
    hif_setmodels(pipelinemode="automatic")
    hifa_bandpassflag(pipelinemode="automatic")
    hifa_spwphaseup(pipelinemode="automatic")
    hifa_gfluxscaleflag(pipelinemode="automatic")
    hifa_gfluxscale(pipelinemode="automatic")
    hifa_timegaincal(pipelinemode="automatic")
    hif_applycal(pipelinemode="automatic")
    hif_makeimlist(intent='PHASE,BANDPASS')
    hif_makeimages(pipelinemode="automatic")
    hif_makeimlist(per_eb=True, intent='CHECK')
    hif_makeimages(pipelinemode="automatic")
    hifa_imageprecheck(pipelinemode="automatic")
    hif_checkproductsize(maxproductsize=350.0, maxcubesize=40.0, maxcubelimit=60.0)
finally:
    h_save()
